In [1]:
import pandas as pd 
import numpy as np

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
df =pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
df['folwer'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   folwer  
0       0  
1       0  
2       0  
3       0  
4       0

In [9]:
df['flower'] = df['folwer'].apply(lambda x : iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   folwer  flower  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,Y_train,Y_test = train_test_split(iris.data,iris.target,test_size = 0.25)

In [12]:
# here we use SVM model

In [13]:
from sklearn import svm
model = svm.SVC(kernel = 'rbf' , C = 30, gamma= 'auto')

In [14]:
model.fit(X_train,Y_train)

SVC(C=30, gamma='auto')

In [15]:
model.score(X_test,Y_test)

0.8947368421052632

In [16]:
#there are you can go train split process repeate model sore varry each time
# ie. you must use Corss val i use 5 step

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
cross_val_score(svm.SVC(kernel = 'linear',C = 10,gamma = 'auto'),iris.data,iris.target,cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
cross_val_score(svm.SVC(kernel = 'rbf',C = 20,gamma = 'auto'),iris.data,iris.target,cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [20]:
cross_val_score(svm.SVC(kernel = 'rbf',C = 10,gamma = 'auto'),iris.data,iris.target,cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [21]:
# above methode same written but i use for loop

In [22]:
kernels = ['rbf','linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel = kval, C= cval,gamma = 'auto'),iris.data,iris.target,cv = 5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
            #avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
avg_scores          

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [23]:
#From above results we can say that rbf with C=1 or 10 or linear with C=1 will give best performance

#Approach 3: Use GridSearchCV
#GridSearchCV does exactly same thing as for loop above but in a single line of code

In [31]:
from sklearn.model_selection import GridSearchCV
gsc = GridSearchCV(svm.SVC(gamma = 'auto'),{
    'C': [1,10,20],
    'kernel': ['linear','rbf']
},cv =5,return_train_score = False)
gsc.fit(iris.data,iris.target)
gsc.cv_results_

{'mean_fit_time': array([0.00139828, 0.00139809, 0.00159883, 0.0013979 , 0.00099826,
        0.00099964]),
 'std_fit_time': array([4.88852431e-04, 4.89688012e-04, 4.89300334e-04, 4.88871408e-04,
        1.57428494e-06, 5.30983387e-07]),
 'mean_score_time': array([0.00099883, 0.00060062, 0.00079966, 0.00100036, 0.00040021,
        0.00039964]),
 'std_score_time': array([5.35248383e-07, 4.90409003e-04, 3.99830815e-04, 6.33846999e-04,
        4.90155145e-04, 4.89453691e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'ker

In [34]:
df = pd.DataFrame(gsc.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001398  4.888524e-04         0.000999    5.352484e-07       1   
1       0.001398  4.896880e-04         0.000601    4.904090e-04       1   
2       0.001599  4.893003e-04         0.000800    3.998308e-04      10   
3       0.001398  4.888714e-04         0.001000    6.338470e-04      10   
4       0.000998  1.574285e-06         0.000400    4.901551e-04      20   
5       0.001000  5.309834e-07         0.000400    4.894537e-04      20   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.900000           0.966667                1.0   
3                1.0           0.966667           0.966667                1.0   
4                1.0           0.900000           0.933333                1.0   
5                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.973333        0.038873                4  
3         0.980000        0.016330                1  
4         0.966667        0.042164                6  
5         0.966667        0.036515                5

In [45]:
df = df[['param_C','param_kernel','mean_test_score']]
df

param_C param_kernel  mean_test_score
0       1       linear         0.980000
1       1          rbf         0.980000
2      10       linear         0.973333
3      10          rbf         0.980000
4      20       linear         0.966667
5      20          rbf         0.966667

In [46]:
gsc.best_params_
 

{'C': 1, 'kernel': 'linear'}

In [47]:
gsc.best_score_

0.9800000000000001

In [48]:
dir(gsc)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [49]:
#Use RandomizedSearchCV to reduce number of iterations and with random combination of parameters. 
#This is useful when you have too many parameters to try and your training time is longer. 
#It helps reduce the cost of computation

In [70]:
from sklearn.model_selection import RandomizedSearchCV

In [71]:
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    'C':[1,10,20],
    'kernel':['linear','rbf']
    
},cv = 5,return_train_score = False,n_iter =2)
rs.fit(iris.data,iris.target)
rs

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['linear', 'rbf']})

In [72]:
rs.cv_results_

{'mean_fit_time': array([0.0013988 , 0.00100017]),
 'std_fit_time': array([0.0007993 , 0.00063264]),
 'mean_score_time': array([0.00059948, 0.00059905]),
 'std_score_time': array([0.00048947, 0.00048912]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[10, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 10}, {'kernel': 'linear', 'C': 10}],
 'split0_test_score': array([0.96666667, 1.        ]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98      , 0.97333333]),
 'std_test_score': array([0.01632993, 0.03887301]),
 'rank_test_score': array([1, 2])}

In [73]:
df = pd.DataFrame(rs.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001399      0.000799         0.000599        0.000489          rbf   
1       0.001000      0.000633         0.000599        0.000489       linear   

  param_C                         params  split0_test_score  \
0      10     {'kernel': 'rbf', 'C': 10}           0.966667   
1      10  {'kernel': 'linear', 'C': 10}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.973333        0.038873                2

In [74]:
df = df[['param_C','param_kernel','mean_test_score']]
df

param_C param_kernel  mean_test_score
0      10          rbf         0.980000
1      10       linear         0.973333

In [75]:
rs.best_params_

{'kernel': 'rbf', 'C': 10}

In [76]:
rs.best_score_

0.9800000000000001

In [65]:
dir(rs)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_iter',
 'n_jobs',
 'n_splits_',
 'param_di

In [77]:

#How about different models with different hyperparameters?

In [78]:
from sklearn.ensemble import RandomForestClassifier

In [112]:
from sklearn.linear_model import LogisticRegression

In [82]:
from sklearn.svm import SVC

In [88]:
from sklearn.tree import DecisionTreeClassifier

In [124]:
model_params = {
    'svm':{
        'model': svm.SVC(gamma = 'auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['linear','rbf']
        }
    },
    'Random_Forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[10,20,40]
        }
    },
    'Logistic_reg':{
            'model':LogisticRegression(solver='liblinear',multi_class='auto'),
            'params':{
                'C':[1,5,10]
        }
        
    },
    'tree':{
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion':['gini','entropy'],
        }
    }
}

In [125]:
scores = []
for model_name, mp in model_params.items():
    gsc = GridSearchCV(mp['model'],mp['params'],cv =5,return_train_score = False)
    gsc.fit(iris.data,iris.target)
    scores.append({
        'model': model_name,
        'best_score': gsc.best_score_,
        'best_params': gsc.best_params_,
    })
scores
    

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_params': {'C': 1, 'kernel': 'linear'}},
 {'model': 'Random_Forest',
  'best_score': 0.9666666666666668,
  'best_params': {'n_estimators': 10}},
 {'model': 'Logistic_reg',
  'best_score': 0.9666666666666668,
  'best_params': {'C': 5}},
 {'model': 'tree',
  'best_score': 0.9666666666666668,
  'best_params': {'criterion': 'gini'}}]

In [126]:
df = pd.DataFrame(scores, columns = ['model','best_score','best_params'])
df

model  best_score                   best_params
0            svm    0.980000  {'C': 1, 'kernel': 'linear'}
1  Random_Forest    0.966667          {'n_estimators': 10}
2   Logistic_reg    0.966667                      {'C': 5}
3           tree    0.966667         {'criterion': 'gini'}

In [ ]:
#
#Based on above, I can conclude that SVM with C=1 and kernel='rbf' is the best model for solving my problem of iris flower classification